# Generated by Django 5.2.6 on 2026-02-25 12:43

from django.db import migrations, models, connection


def set_default_values(apps, schema_editor):
    """
    Set default values for existing records where is_email_verified is NULL
    """
    Account = apps.get_model('accounts', 'Account')
    Account.objects.filter(is_email_verified__isnull=True).update(is_email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_is_active'),
    ]

    operations = [
        # First, set NULL values to False for existing records
        migrations.RunPython(set_default_values, migrations.RunPython.noop),
        
        # Then make the field NOT NULL with default
        migrations.AlterField(
            model_name='account',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
