# Generated by Django 5.2.6 on 2026-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
