# Generated by Django 5.2.6 on 2026-02-26 07:57

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Business/Store name', max_length=200)),
                ('business_category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing & Fashion'), ('FOOD', 'Food & Beverages'), ('HOME', 'Home & Garden'), ('SPORTS', 'Sports & Outdoors'), ('BOOKS', 'Books & Media'), ('TOYS', 'Toys & Games'), ('HEALTH', 'Health & Beauty'), ('AUTOMOTIVE', 'Automotive'), ('OTHER', 'Other')], max_length=20)),
                ('business_description', models.TextField(blank=True, help_text='Describe your business')),
                ('business_phone', models.CharField(help_text='Business contact number', max_length=25)),
                ('business_email', models.EmailField(help_text='Business email address', max_length=155)),
                ('store_location', models.CharField(blank=True, help_text='Physical store location (optional)', max_length=500)),
                ('store_city', models.CharField(blank=True, max_length=50)),
                ('store_state', models.CharField(blank=True, max_length=50)),
                ('nid_card_front', cloudinary.models.CloudinaryField(help_text='Front side of NID card', max_length=255, verbose_name='nid_card_front')),
                ('nid_card_back', cloudinary.models.CloudinaryField(help_text='Back side of NID card', max_length=255, verbose_name='nid_card_back')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about approval/rejection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['-created_at'],
            },
        ),
    ]
