# Generated by Django 5.2.6 on 2026-02-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vendor'),
        ('product', '0013_remove_product_product_product_slug_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='Product approval status', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin-added products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.vendor'),
        ),
    ]
